#!/bin/bash
# Download all source files from GitHub raw
BASE="https://raw.githubusercontent.com/wjpyinuo/DotTranslator/main"

FILES=(
  ".github/workflows/ci.yml"
  ".gitignore"
  "DotStats/package.json"
  "DotStats/electron/main.ts"
  "DotStats/electron/preload.ts"
  "DotStats/index.html"
  "DotStats/postcss.config.js"
  "DotStats/src/App.tsx"
  "DotStats/src/components/Overview/Overview.tsx"
  "DotStats/src/components/WebSocket/useWebSocket.ts"
  "DotStats/src/main.tsx"
  "DotStats/src/stores/statsStore.ts"
  "DotStats/src/styles/dashboard.css"
  "DotStats/tailwind.config.js"
  "DotStats/tsconfig.json"
  "DotStats/vite.config.ts"
  "DotStats/server/package.json"
  "DotStats/server/Dockerfile"
  "DotStats/server/docker-compose.yml"
  "DotStats/server/.dockerignore"
  "DotStats/server/.env.example"
  "DotStats/server/.gitignore"
  "DotStats/server/db/init.sql"
  "DotStats/server/nginx/nginx.conf"
  "DotStats/server/package-lock.json"
  "DotStats/server/src/db/pool.ts"
  "DotStats/server/src/index.ts"
  "DotStats/server/src/middleware/auth.ts"
  "DotStats/server/src/routes/admin.ts"
  "DotStats/server/src/routes/events.ts"
  "DotStats/server/src/routes/health.ts"
  "DotStats/server/src/routes/stats.ts"
  "DotStats/server/src/services/redis.ts"
  "DotStats/server/src/services/websocket.ts"
  "DotStats/server/src/tasks/alerts.ts"
  "DotStats/server/src/tasks/cron.ts"
  "DotStats/server/tests/routes/events.test.ts"
  "DotStats/server/tests/routes/health.test.ts"
  "DotStats/server/tests/routes/stats.test.ts"
  "DotStats/server/tests/unit/cron.test.ts"
  "DotStats/server/tsconfig.json"
  "DotStats/server/vitest.config.ts"
  "PRIVACY.md"
  "README.md"
  "electron/main.ts"
  "electron/preload.ts"
  "eslint.config.js"
  "index.html"
  "package.json"
  "pnpm-workspace.yaml"
  "postcss.config.js"
  "src/main/database.ts"
  "src/renderer/App.tsx"
  "src/renderer/components/HistoryList/HistoryList.tsx"
  "src/renderer/components/InputArea/InputArea.tsx"
  "src/renderer/components/SettingsPanel/SettingsPanel.tsx"
  "src/renderer/components/StatsPage/StatsPage.tsx"
  "src/renderer/components/TitleBar/TitleBar.tsx"
  "src/renderer/components/TranslationPanel/TranslationPanel.tsx"
  "src/renderer/main.tsx"
  "src/renderer/stores/appStore.ts"
  "src/renderer/styles/app.css"
  "src/shared/constants/index.ts"
  "src/shared/types/electron.d.ts"
  "src/shared/types/index.ts"
  "src/telemetry/reporter.ts"
  "src/workers/translation/providers/baidu.ts"
  "src/workers/translation/providers/deepl.ts"
  "src/workers/translation/providers/google.ts"
  "src/workers/translation/router.ts"
  "tailwind.config.js"
  "tsconfig.json"
  "vite.config.ts"
)

for f in "${FILES[@]}"; do
  dir=$(dirname "$f")
  mkdir -p "$dir"
  curl -sL "$BASE/$f" -o "$f" 2>/dev/null
  if [ $? -eq 0 ]; then
    echo "✓ $f"
  else
    echo "✗ $f"
  fi
done
